FROM ubuntu:24.04

WORKDIR /SnowK

RUN mkdir -p logs &&\
    mkdir -p data &&\
    mkdir -p conf &&\
    mkdir -p bin

COPY ./build/transmite_server bin/
COPY ./depends/ /lib/x86_64-linux-gnu/
# COPY ./nc /bin/

CMD bin/transmite_server -flagfile=conf/transmite_server.conf