FROM ubuntu:24.04

WORKDIR /SnowK

RUN mkdir -p logs &&\
    mkdir -p data &&\
    mkdir -p conf &&\
    mkdir -p bin

COPY ./build/message_server bin/
COPY ./depends/ /lib/x86_64-linux-gnu/
# COPY ./nc /bin/

CMD bin/message_server -flagfile=conf/message_server.conf