FROM ubuntu:24.04

WORKDIR /SnowK

RUN mkdir -p logs &&\
    mkdir -p data &&\
    mkdir -p conf &&\
    mkdir -p bin

COPY ./build/gateway_server bin/
COPY ./depends/ /lib/x86_64-linux-gnu/
COPY ./nc /bin/

CMD bin/gateway_server -flagfile=conf/gateway_server.conf