FROM ubuntu:24.04

WORKDIR /SnowK

RUN mkdir -p logs &&\
    mkdir -p data &&\
    mkdir -p conf &&\
    mkdir -p bin

COPY ./build/file_server bin/
COPY ./depends/ /lib/x86_64-linux-gnu/
# COPY ./nc /bin/

CMD bin/file_server -flagfile=conf/file_server.conf